In [1]:
import os
import zipfile
import urllib.request
import pandas as pd
import numpy as np
import datetime

In [2]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [3]:
cd drive/MyDrive/Redit data/

/content/drive/MyDrive/Redit data

In [4]:
pd_posts = pd.read_csv('crypto_aug_comments.csv')
pd_posts

            type       id  ... sentiment score
0        comment  hb4hdni  ...    0.8885     1
1        comment  hb4hd3u  ...       NaN     1
2        comment  hb4hbyc  ...       NaN     1
3        comment  hb4hbge  ...       NaN     1
4        comment  hb4hb1u  ...       NaN     1
...          ...      ...  ...       ...   ...
3756092  comment  h79bjku  ...    0.6249     1
3756093  comment  h79bhmb  ...       NaN     1
3756094  comment  h79bftq  ...       NaN     1
3756095  comment  h79beot  ...       NaN     1
3756096  comment  h79bd06  ...    0.3182     1

[3756097 rows x 10 columns]

In [5]:
data = pd_posts[["created_utc", "body", "sentiment"]]
data.head()

   created_utc                                               body  sentiment
0   1630454394  Be sure to do your own diligence. Assume that ...     0.8885
1   1630454387                                          [removed]        NaN
2   1630454372                                          [removed]        NaN
3   1630454366                                          [removed]        NaN
4   1630454360                                          [removed]        NaN

In [6]:
d_data = data[data["body"]!="[removed]"]
d_data["body"] = data["body"].str.lower() # TODO: fix warning
# ...

d_data

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

         created_utc  ... sentiment
0         1630454394  ...    0.8885
16        1630454262  ...    0.3182
24        1630454212  ...    0.8885
37        1630454139  ...    0.3182
45        1630454098  ...    0.3182
...              ...  ...       ...
3756088   1627776256  ...    0.6249
3756089   1627776248  ...    0.8854
3756091   1627776212  ...    0.7339
3756092   1627776211  ...    0.6249
3756096   1627776110  ...    0.3182

[3280072 rows x 3 columns]

In [7]:
#drop null row if any
d_data = d_data.dropna()

In [8]:
#extract comments relative to word 'bitcoin'
d_data = d_data[d_data['body'].str.contains("bitcoin")]

**SPAM ALERT- this should be removed**

In [ ]:
pd_posts['body'][1]

"**your submission has been removed because 1 submission with a similar title has been posted on the subreddit in the past.**\n\n**op:** /u/mamihasonline\n\n**date:** 2021-08-29 06:21:14\n\n**duplicates:**\n\nn | user | date | posted... | similarity | title\n:-:|:-:|:-:|:-:|:-:|:-:|:-:\n1| [/u/orkun1903](https://www.reddit.com/user/orkun1903) | 2021-08-28 20:59:28 | 9 hours 21 minutes before | [95%](https://www.reddit.com/r/cryptomoonshots/comments/pdhtr5/minibitcoinmbtc_bitcoin_reward_token_fair/) | [minibitcoin(mbtc) - bitcoin reward token | fair launched | lp locked for a ...](https://redd.it/pdhtr5)\n\n\ni am a bot. if you believe this was sent in error, reply to this comment and a moderator will review your post. **do not delete your post or moderators won't be able to review it.**"

In [ ]:
pd_posts[pd_posts['body'].str.contains("your submission has been removed because")]

    Unnamed: 0  ...  sentiment
1        26530  ...     0.5859
2        32642  ...    -0.4767
3        32908  ...    -0.4767
8        80675  ...     0.8148
10      104891  ...    -0.2960
22      186188  ...     0.0772
23      190271  ...     0.0772
24      195118  ...     0.1739
27      210068  ...     0.3436
53      338686  ...     0.3182
54      341846  ...    -0.4019
55      342287  ...    -0.4019
57      348139  ...    -0.4019
60      357340  ...    -0.1027
62      364134  ...     0.1027

[15 rows x 4 columns]

In [9]:
# removing it from dataset
df = d_data[d_data["body"].str.contains("your submission has been removed because") == False]

In [12]:
#RESETTING INDEX
df = df.reset_index(drop=True)

In [10]:
df[df['body'].str.contains("\(")]

         created_utc  ... sentiment
235640    1628595376  ...   -0.7569
245149    1628532152  ...    0.1540
344352    1627888356  ...    0.5859
367962    1630353922  ...    0.6351
369004    1630245977  ...    0.0000
...              ...  ...       ...
3732873   1627776860  ...    0.8385
3733289   1627776228  ...   -0.9118
3733470   1627776006  ...    0.8385
3733612   1630443668  ...    0.7783
3755002   1627911823  ...    0.9168

[11219 rows x 3 columns]

**SPAM ALERT- this should be removed**

In [13]:
df['body'][54250]

"* **bitcoin [pros](https://old.reddit.com/r/cryptocurrency/comments/og1fha/rcryptocurrency_cointest_top_10_category_bitcoin/) &amp; [cons](https://old.reddit.com/r/cryptocurrency/comments/og1gjd/rcryptocurrency_cointest_top_10_category_bitcoin/)** - participate in the r\\/cc [cointest](https://old.reddit.com/r/cryptocurrency/wiki/cointest_policy) to potentially win moons. prize allocations: 1st - 300, 2nd - 150, 3rd - 75.. check the [archive](https://old.reddit.com/r/cryptocurrency/wiki/cointest_archive) for past results.\n\n* sort comments as controversial first by [clicking here](https://www.reddit.com/r/cryptocurrency/comments/ovi39t/bear_market_over_why_bitcoin_could_soar_to_45k_as/?sort=controversial). doesn't work on mobile.\n\n---        \n\n*i am a bot, and this action was performed automatically. please [contact the moderators of this subreddit](/message/compose/?to=/r/cryptocurrency) if you have any questions or concerns.*"

In [14]:
df[df['body'].str.contains("i am a bot, and this action was performed automatically")]

       created_utc  ... sentiment
384     1630454258  ...    0.8385
390     1630453712  ...    0.8385
406     1630452540  ...    0.8385
408     1630452465  ...    0.8385
438     1630450632  ...    0.8385
...            ...  ...       ...
54224   1627779170  ...    0.8385
54228   1627778655  ...    0.8385
54243   1627776963  ...    0.8385
54250   1627776860  ...    0.8385
54263   1627776006  ...    0.8385

[5419 rows x 3 columns]

In [15]:
df['body'][390]

"* **[vechain](https://en.bitcoinwiki.org/wiki/vechain) [pros](https://old.reddit.com/r/cryptocurrency/wiki/cointest_archive#wiki_vet_pros) &amp; [cons](https://old.reddit.com/r/cryptocurrency/wiki/cointest_archive#wiki_vet_cons)** - participate in the r\\/cc [cointest](https://old.reddit.com/r/cryptocurrency/wiki/cointest_policy) to potentially win moons. prize allocations: 1st - 300, 2nd - 150, 3rd - 75.\n\n* sort comments as controversial first by [clicking here](https://www.reddit.com/r/cryptocurrency/comments/pfhusc/vpunks_the_vechain_version_of_cryptopunks_has_hit/?sort=controversial). doesn't work on mobile.\n\n---\n\n*i am a bot, and this action was performed automatically. please [contact the moderators of this subreddit](/message/compose/?to=/r/cryptocurrency) if you have any questions or concerns.*"

In [16]:
#removing
df = df[df["body"].str.contains("i am a bot, and this action was performed automatically") == False]

In [ ]:
df[df['body'].str.contains("\(")]

       Unnamed: 0  ...  sentiment
23             32  ...    -0.7569
25             34  ...     0.1540
44             56  ...     0.5859
51             66  ...     0.6351
53             68  ...     0.0000
...           ...  ...        ...
54227       54242  ...     0.6124
54239       54254  ...     0.5256
54262       54277  ...    -0.9118
54264       54279  ...     0.7783
54280       54295  ...     0.9168

[5800 rows x 5 columns]

In [ ]:
df['body'][54227]

'this is from the website... [https://docs.smartbch.org/smartbch/faq](https://docs.smartbch.org/smartbch/faq)\n\nq: what is smartbch?\n\nsmartbch is a sidechain for bitcoin cash and has an aim to explore new ideas and unlock novel possibilities. a sidechain is a blockchain designed for fast and inexpensive transactions with a special relationship with the main chain because of a two-way peg; in this case between bitcoin cash and smartbch.\n\nthis is liquid for bch.'

In [ ]:
df[df['body'].str.contains(":")]

       Unnamed: 0  ...  sentiment
44             56  ...     0.5859
45             58  ...    -0.8221
53             68  ...     0.0000
54             69  ...     0.3612
55             70  ...     0.7127
...           ...  ...        ...
54262       54277  ...    -0.9118
54266       54281  ...     0.0000
54267       54282  ...     0.9601
54268       54283  ...     0.0000
54280       54295  ...     0.9168

[4946 rows x 5 columns]

In [ ]:
df['body'][55]

'boom nieuw gem just saw this amazing new project and this is going to the moon you are all still early launching real soon on the doxxed dev on video vc bnb hc biggest buy back in history only trushtworty influencers in this agency made revenue going back in to the project bnb bitcoin join the telegram'

In [ ]:
df['body'][48857]

'found a really cool project taboo the playboy of crypto that got featured in newsbtc bitcoinist and business insider'

In [17]:
df.drop_duplicates().reset_index(drop=True)

       created_utc  ... sentiment
0       1630433705  ...    0.0000
1       1629919425  ...    0.8074
2       1629842310  ...    0.4215
3       1629842242  ...   -0.0516
4       1629817640  ...    0.8555
...            ...  ...       ...
48856   1628483471  ...    0.4900
48857   1628128731  ...   -0.2500
48858   1628032031  ...   -0.4760
48859   1628006526  ...    0.0000
48860   1627911823  ...    0.9168

[48861 rows x 3 columns]

In [25]:
import re
import nltk

In [26]:
from nltk.corpus import stopwords
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.

True

In [27]:
#stp word removal is very imp in sentiment analysis
STOPWORDS=stopwords.words('english')
def cleaning_stopwords(text):
    return " ".join([word for word in str(text).split() if word not in STOPWORDS])
df['body'] = df['body'].apply(lambda text: cleaning_stopwords(text))

df['body'].head()

0         thats exactly everyone always said bitcoin..
1    yeah expected , peoples like would coin except...
2    mined bitcoin 2012, still reddit trolling post...
3    would use telegram scam group join video call ...
4    feels nice get free bitcoin holding this. stak...
Name: body, dtype: object

In [29]:
#cleaning new lines
def cleaning_newlines(data):
    return re.sub(r'\n','',data)
df['body'] = df['body'].apply(lambda x: cleaning_newlines(x))

In [30]:
def cleaning_URLs(data):
    return re.sub('(https?:\/\/)?([\da-z\.-]+)\.([a-z\.]{2,6})([\/\w \.-]*)','',data)
df['body'] = df['body'].apply(lambda x: cleaning_URLs(x))

In [31]:
def cleaning_sqbracket(data):
    return re.sub('\[[^)]*\]','',data)
df['body'] = df['body'].apply(lambda x: cleaning_sqbracket(x))

In [32]:
def cleaning_parenthesis(data):
    return re.sub('\([^)]*\)','',data)
df['body'] = df['body'].apply(lambda x: cleaning_parenthesis(x))

In [33]:
def cleaning_unicodedemojis(data):
    return re.sub('(\u00a9|\u00ae|[\u2000-\u3300]|\ud83c[\ud000-\udfff]|\ud83d[\ud000-\udfff]|\ud83e[\ud000-\udfff])','',data)
df['body'] = df['body'].apply(lambda x: cleaning_unicodedemojis(x))

In [34]:
GOOD_SYMBOLS_RE = re.compile('[^a-z]')
#Removing any character other than those of described above
def filter_out_uncommon_symbols(text):
    return GOOD_SYMBOLS_RE.sub(' ', text)
df['body'] = df['body'].apply(lambda x: filter_out_uncommon_symbols(x))

In [35]:
def strip_text(text):
    return re.sub('  +',' ',text)
df['body'] = df['body'].apply(lambda x: strip_text(x))

In [ ]:
#df.to_csv('26Jan2022.csv')